name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yml
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      version: ${{ github.run_number }}
