name: Build Binary

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          scripts/build.sh build/dstack-sshproxy-$GOOS-$GOARCH ${{ inputs.version }}
      - id: upload
        uses: actions/upload-artifact@v7
        with:
          name: dstack-sshproxy
          path: build/dstack-sshproxy-*
          retention-days: 1
